name: TestCustom
on:
  workflow_dispatch:
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testAkCustomAction
        uses: KumarAkshayThakur/Customaction@v1

 
